# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpal-interface/force_sensor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpal-interface/force_sensor.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!rpal-interface/force_sensor.proto\"8\n\x12\x46orceSensorMessage\x12\n\n\x02\x66x\x18\x01 \x01(\x01\x12\n\n\x02\x66y\x18\x02 \x01(\x01\x12\n\n\x02\x66z\x18\x03 \x01(\x01\x62\x06proto3'
)




_FORCESENSORMESSAGE = _descriptor.Descriptor(
  name='ForceSensorMessage',
  full_name='ForceSensorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fx', full_name='ForceSensorMessage.fx', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fy', full_name='ForceSensorMessage.fy', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fz', full_name='ForceSensorMessage.fz', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['ForceSensorMessage'] = _FORCESENSORMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ForceSensorMessage = _reflection.GeneratedProtocolMessageType('ForceSensorMessage', (_message.Message,), {
  'DESCRIPTOR' : _FORCESENSORMESSAGE,
  '__module__' : 'rpal_interface.force_sensor_pb2'
  # @@protoc_insertion_point(class_scope:ForceSensorMessage)
  })
_sym_db.RegisterMessage(ForceSensorMessage)


# @@protoc_insertion_point(module_scope)
